### PR TITLE
Bind to CPU 1

### PR DESCRIPTION
**Pull request by mattgodbolt**

### CODE REVIEW

**Comment by rmmh** [comment]
Did this help you much with jank? The length of the test functions should be much smaller than the interval between kernel ticks, so context switches and migrations _should_ be rare.

**Comment by mattgodbolt** [comment]
Not enough really, given all the other things going on..Feel free to ignore!

**Comment by rmmh** [comment]
OK. CPU isolation techniques to reduce jitter are interesting, but they're probably easier to iterate on using a shell script harness that invokes tasksel/nice/cpusets/...

**Comment by mattgodbolt** [comment]
Fair point (see the recent rdpmc PR too...there must be a better way!)

**Pull request closed without merging**
